
/***** LOAD FINREPO_PAY_PERIOD_13MTH_VW DATA INTO FINREPO *****/ 
TRUNCATE TABLE FINCOMM_PAY_PERIOD_13MTH;

INSERT INTO FINCOMM.FINCOMM_PAY_PERIOD_13MTH
 (PAY_PERIOD_ID, PP_NUM, MONTH_ID, PAYOUT_IND, CHEQUE_DATE,
  QUARTER_ID, QTR_PAYOUT_IND, QUARTER_SIX_ID, QTR_PAYOUT_SIX_IND,
  GTM_MONTH_ID)

SELECT 
 PAY_PERIOD_ID, PP_NUM, MONTH_ID, PAYOUT_IND, CHEQUE_DATE,
 QUARTER_ID, QTR_PAYOUT_IND, QUARTER_SIX_ID, QTR_PAYOUT_SIX_IND,
 GTM_MONTH_ID   
FROM
   HRW.FINREPO_PAY_PERIOD_13MTH_VW@HRWP.WORLD;
   
COMMIT; 
   

/***** LOAD ANY NEW PAY PERIODS INTO TMP_HR_JEID_PP *****/ 
INSERT INTO FINCOMM.COM_HR_JEID_PP
 (YR_MTH, PP_ID, PROCESSED, TO_BE_PROCESSED)
SELECT 
 to_char(p.cheque_date,'YYYYMM') AS YR_MTH,
 P.PAY_PERIOD_ID AS PP_ID,
 'N' AS PROCESSED,
 'N' AS TO_BE_PROCESSED
FROM 
 FINCOMM.FINCOMM_PAY_PERIOD_13MTH P
 LEFT JOIN FINCOMM.COM_HR_JEID_PP H
  ON
   P.PAY_PERIOD_ID = H.PP_ID 
WHERE
 TO_NUMBER(SUBSTR(P.PAY_PERIOD_ID,0,4)) >= 2019 AND
 H.PP_ID IS NULL   
ORDER BY 2,1;

COMMIT;

 
/***** SET THE TO BE PROCESSED FLAG IN TOE TMP_HR_JEID_PP TABLE FOR PERIOS TO LOAD AND PROCESS *****/
MERGE INTO FINCOMM.COM_HR_JEID_PP PP
USING
 (
  SELECT 
    P.PAY_PERIOD_ID AS PP_ID
  FROM 
   FINCOMM.FINCOMM_PAY_PERIOD_13MTH P
   INNER JOIN FINCOMM.COM_HR_JEID_PP H
    ON
     P.PAY_PERIOD_ID = H.PP_ID
  WHERE
   H.PROCESSED = 'N' AND
   P.CHEQUE_DATE <= SYSDATE and -- use when run is after month end
   to_number(to_char(p.cheque_date,'YYYYMM')) < to_number(to_char(sysdate,'YYYYMM')) -- use when run is after month end
   --to_number(to_char(p.cheque_date,'YYYYMM')) = to_number(to_char(sysdate,'YYYYMM')) -- use when run is before month end
 ) X
ON 
 (X.PP_ID = PP.PP_ID)
WHEN MATCHED THEN
 UPDATE
  SET PP.TO_BE_PROCESSED = 'Y';
COMMIT;  

/***** RELOAD FINREPO_SF_REP_TRANS_VW *****/
TRUNCATE TABLE FINCOMM.FINCOMM_SF_REP_TRANS;

INSERT INTO FINCOMM.FINCOMM_SF_REP_TRANS
 (HOME_DB, KGEN_PAYEEID, CUSTOMER_ID, EAID, PAY_PERIOD_ID,
  PAY_PERIOD_WEST_ID, COMP_YEAR, COMP_QTR, CHANNEL, PRODUCT_ID,
  DIV_NUM, CREW_CODE, OFFICE_CODE, UDAC_CODE, PRODUCT_GROUP,
  ITEM_ID, SV_ITEM_ID, SV_ITEM_ID_ISSUE_NUM, ASSIGNMENT_TYPE, WW_CUSTOMER_ID,
  WW_EAID, PRODUCT_CODE, PRODUCT_ISSUE_NUM, PRODUCT_TYPE, CUST_TYPE, 
  UNQ_PI_AMT, PI_AMT, NI_AMT, EXTRACT_DATE, CREATED_BY, 
  CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, TRANS_ID)
 
SELECT
 T.HOME_DB, T.KGEN_PAYEEID, T.CUSTOMER_ID, T.EAID, T.PAY_PERIOD_ID,
 T.PAY_PERIOD_WEST_ID, T.COMP_YEAR, T.COMP_QTR, T.CHANNEL, T.PRODUCT_ID,
 T.DIV_NUM, T.CREW_CODE, T.OFFICE_CODE, T.UDAC_CODE, T.PRODUCT_GROUP,
 T.ITEM_ID, T.SV_ITEM_ID, T.SV_ITEM_ID_ISSUE_NUM, T.ASSIGNMENT_TYPE, T.WW_CUSTOMER_ID,
 T.WW_EAID, T.PRODUCT_CODE, T.PRODUCT_ISSUE_NUM, T.PRODUCT_TYPE, T.CUST_TYPE, 
 T.UNQ_PI_AMT, T.PI_AMT, T.NI_AMT, T.EXTRACT_DATE, 
 'HRWP', SYSDATE, 'HRWP', SYSDATE, T.ROWID
FROM
  HRW.FINREPO_SF_REP_TRANS_VW@HRWP.WORLD T;
  
COMMIT;  


TRUNCATE TABLE FINCOMM_NCCP_CUSTDET_RPT;
  
/**** ADD IN THE COM_PAYOUT_IND HERE ****/
INSERT INTO FINCOMM.FINCOMM_NCCP_CUSTDET_RPT N
 (HOME_DB, PRODUCT_TYPE, PAY_PERIOD_ID, KGEN_PAYEEID, CUSTOMER_ID,
  COMP_YEAR, CHANNEL, CUSTOMER_NAME, PERIODSEQ, PI_AMT,
  NI_AMT, RENEWAL_AMT, INCREASE_AMT, NEW_AMT, RENEWAL_RATE,
  INCREASE_RATE, NEW_RATE, COM_AMT, COM_IND, EXTRACT_DATE,
  THRYV_NI_AMT, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE, COM_PAYOUT_IND,
  DAR_NI_AMT, TYPE_NUM, PRODUCT_TYPE_TYPE, SORT_NUM, MONTH_ID)

SELECT /*+ DRIVING_SITE(C) */
 C.HOME_DB, C.PRODUCT_TYPE, C.PAY_PERIOD_ID, C.KGEN_PAYEEID, C.CUSTOMER_ID,
 C.COMP_YEAR, C.CHANNEL, C.CUSTOMER_NAME, C.PERIODSEQ, C.PI_AMT,
 C.NI_AMT, C.RENEWAL_AMT, C.INCREASE_AMT, C.NEW_AMT, C.RENEWAL_RATE,
 C.INCREASE_RATE, C.NEW_RATE, C.COM_AMT, C.COM_IND, C.EXTRACT_DATE,
 C.THRYV_NI_AMT, 'HRWP', SYSDATE, 'HRWP', SYSDATE, COM_PAYOUT_IND,
 DAR_NI_AMT, TYPE_NUM, PRODUCT_TYPE_TYPE, SORT_NUM, MONTH_ID
FROM 
 HRW.FINREPO_NCCP_CUSTDET_RPT_VW@HRWP.WORLD C;
COMMIT;                       

/***** LOAD FINREPO_PH_NCCP_PP_DETAIL_VW BASED ON SELECTED PAY PERIODS *****/
TRUNCATE TABLE FINCOMM.FINCOMM_PH_NCCP_PP_DETAIL;

INSERT INTO FINCOMM.FINCOMM_PH_NCCP_PP_DETAIL 
 (PAY_PERIOD_ID, PAID_PAY_PERIOD_ID, FINALIZE_IND, FINALIZE_DATE, REP_NUM,
  IS_FIRST, IS_LAST, EMP_NAME, FIRST_NAME, LAST_NAME, 
  DIV_NUM, UNIT_NUM, OFFICE_CODE, CHANNEL, TITLE_CODE,
  RATE_BAND, UNION_NAME, COLA_RATES_IND, DSM_NUM, HR_HIRE_DATE,
  TERM_DATE, HIGH_PAYOUT_IND, TOTAL_PP_INCENTIVE_AMT, TARGET_INCENTIVE_AMT, PCT_TO_TARGET_PCT,
  PI_AMT, NI_AMT, RENEWAL_AMT, INCREASE_AMT, NEWNON_AMT, 
  RENEWAL_RATE, INCREASE_RATE, NEWNON_RATE, SEM_NNI_RATE, RENEWAL_COM_AMT,
  INCREASE_COM_AMT, NEWNON_COM_AMT, TOTAL_COM_AMT, SEM_PI_AMT, SEM_NI_AMT,
  SEM_RENEWAL_AMT, SEM_INCREASE_AMT, SEM_NEW_AMT, SEM_RENEWAL_COM, SEM_INCREASE_COM,
  SEM_NEW_COM, SEM_TOTAL_COM, COM_AMT, DEBIT_PRO_ADJ_COM_AMT, NET_COM_AMT,
  BEG_BALANCE_AMT, END_BALANCE_AMT, NEW_H1_CNT, TIP_H1_PCT, MTH_H1_NEW_AMT,
  MTH_H1_BONUS_AMT, MTH_H1_NET_BONUS_AMT, NEW_K1_CNT, TIP_K1_PCT, MTH_K1_NEW_AMT,
  MTH_K1_BONUS_AMT, MTH_K1_NET_BONUS_AMT, NEW_PE_CNT, TIP_PE_PCT, MTH_PE_NEW_AMT,
  MTH_PE_BONUS_AMT, MTH_PE_NET_BONUS_AMT, NEW_T1_NI_AMT, MTH_T1_NNI_AMT, MTH_T1_BONUS_AMT,
  TIP_T1_PCT, MTH_T1_NET_BONUS_AMT, NEW_T3_NI_AMT, MTH_T3_NNI_AMT, MTH_T3_BONUS_AMT,
  TIP_T3_PCT, MTH_T3_NET_BONUS_AMT, NEW_TA_NEW_CNT, MTH_TA_NNI_AMT, MTH_TA_BONUS_AMT,
  TIP_TA_PCT, MTH_TA_NET_BONUS_AMT, MTH_T2_NEW_AMT, MTH_T2_NEW_OBJ_AMT, MTH_T2_PERF_PCT,
  NEW_T2_CNT, MTH_T2_RATE, MTH_T2_TARGET_AMT, MTH_T2_BONUS_AMT, TIP_T2_PCT,
  MTH_T2_NET_BONUS_AMT, MTH_T4_NEW_AMT, MTH_T4_NEW_OBJ_AMT, MTH_T4_PERF_PCT, NEW_T4_CNT,
  MTH_T4_RATE, MTH_T4_TARGET_AMT, MTH_T4_BONUS_AMT, TIP_T4_PCT, MTH_T4_NET_BONUS_AMT,
  TOTAL_BONUS_DUE_AMT, BONUS_PAID_IND, TOTAL_BONUS_PAID_AMT, OTHER_INC_AMT, DISABILITY_INC_AMT,
  SA_INC_AMT, IST_TRAINING_INC_AMT, IST_TRANSITION_INC_AMT, OT_INC_AMT, ADJUST_INC_AMT,
  SA_TYPE, TOTAL_INCENTIVE_AMT, PRIOR_PAID_BALANCE_AMT, PRIOR_UNPAID_BALANCE_AMT, PAYMENT_AMT,
  OFFCYCLE_PAYMENTS_AMT, HIGH_PAYOUT_THLD_PCT, BUDGET_DAYS, IST_TRAINING_DAYS, IST_TRANSISTION_DAYS,
  STD_DAYS, TOTAL_DAYS, YTD_PI_AMT, YTD_NI_AMT, YTD_RENEWAL_AMT,
  YTD_INCREASE_AMT, YTD_NEWNON_AMT, YTD_RENEWAL_COM, YTD_INCREASE_COM, YTD_NEW_COM,
  YTD_COM, YTD_SEM_PI_AMT, YTD_SEM_NI_AMT, YTD_SEM_RENEWAL_AMT, YTD_SEM_INCREASE_AMT,
  YTD_SEM_NEW_AMT, YTD_SEM_RENEWAL_COM, YTD_SEM_INCREASE_COM, YTD_SEM_NEW_COM, YTD_SEM_TOTAL_COM,
  YTD_TOTAL_COM, YTD_TARGET_AMT, NEWNON_CNT, YTD_NEWNON_CNT, YTD_DEBIT_PRO_ADJ_COM_AMT,
  YTD_NET_COM_AMT, YTD_TOTAL_BONUS, BASE_PAY_AMT, YTD_BASE_PAY_AMT,
  PP_ACTIVE, YTD_ACTIVE_PP, YE_YTD_TOTAL_BONUS_AMT, YE_RESTART1_TOTAL_BONUS_AMT, YE_BONUS_COM_DUE,
  YE_BONUS_COM_PAID, YE_YTD_H1_PI_AMT, YE_YTD_H1_NI_AMT, YE_YTD_H1_SN_AMT, YE_YTD_H1_OBJ_PCT,
  YE_YTD_H1_OBJ_SN_AMT, YE_YTD_H1_RATE, YE_YTD_H1_RENEWAL_AMT, YE_YTD_H1_TIP_QUALIFY_IND, YE_YTD_H1_BONUS_AMT,
  YE_YTD_K1_PI_AMT, YE_YTD_K1_NI_AMT, YE_YTD_K1_SN_AMT, YE_YTD_K1_OBJ_PCT, YE_YTD_K1_OBJ_SN_AMT,
  YE_YTD_K1_RATE, YE_YTD_K1_RENEWAL_AMT, YE_YTD_K1_TIP_QUALIFY_IND, YE_YTD_K1_BONUS_AMT, YE_PE_YTD_NEW_AMT,
  YE_PE_YTD_NEW_OBJ_AMT, YE_YTD_PE_NEW_COUNT, YE_YTD_PE_NEW_OBJ_COUNT, YE_YTD_PE_BONUS_QUALIFY_IND, YE_YTD_PE_TIP_QUALIFY_IND,
  YE_YTD_PE_BONUS_AMT, YE_RESTART1_H1_PI_AMT, YE_RESTART1_H1_NI_AMT, YE_RESTART1_H1_SN_AMT, YE_RESTART1_H1_OBJ_PCT,
  YE_RESTART1_H1_OBJ_SN_AMT, YE_RESTART1_H1_RATE, YE_RESTART1_H1_RENEWAL_AMT, YE_RESTART1_H1_TIP_QUALIFY_IND, YE_RESTART1_H1_BONUS_AMT,
  YE_RESTART1_K1_PI_AMT, YE_RESTART1_K1_NI_AMT, YE_RESTART1_K1_SN_AMT, YE_RESTART1_K1_OBJ_PCT, YE_RESTART1_K1_OBJ_SN_AMT,
  YE_RESTART1_K1_RATE, YE_RESTART1_K1_RENEWAL_AMT, YE_RESTART1_K1_TIP_QUALIFY_IND, YE_RESTART1_K1_BONUS_AMT, YE_PE_RESTART1_NEW_AMT,
  YE_PE_RESTART1_NEW_OBJ_AMT, YE_RESTART1_PE_NEW_COUNT, YE_RESTART1_PE_NEW_OBJ_COUNT, YE_RESTART1_PE_BONUS_Q_IND, YE_RESTART1_PE_TIP_QUALIFY_IND,
  YE_RESTART1_PE_BONUS_AMT, EXTRACT_DATE, BONUS_TARGET_AMT, YTD_BONUS_TARGET_AMT)
  
SELECT /*+ DRIVING_SITE(N) */
 N.PAY_PERIOD_ID, N.PAID_PAY_PERIOD_ID, N.FINALIZE_IND, N.FINALIZE_DATE, N.REP_NUM,
 N.IS_FIRST, N.IS_LAST, N.EMP_NAME, N.FIRST_NAME, N.LAST_NAME, 
 N.DIV_NUM, N.UNIT_NUM, N.OFFICE_CODE, N.CHANNEL, N.TITLE_CODE,
 N.RATE_BAND, N.UNION_NAME, N.COLA_RATES_IND, N.DSM_NUM, N.HR_HIRE_DATE,
 N.TERM_DATE, N.HIGH_PAYOUT_IND, N.TOTAL_PP_INCENTIVE_AMT, N.TARGET_INCENTIVE_AMT, N.PCT_TO_TARGET_PCT,
 N.PI_AMT, N.NI_AMT, N.RENEWAL_AMT, N.INCREASE_AMT, N.NEWNON_AMT, 
 N.RENEWAL_RATE, N.INCREASE_RATE, N.NEWNON_RATE, N.SEM_NNI_RATE, N.RENEWAL_COM_AMT,
 N.INCREASE_COM_AMT, N.NEWNON_COM_AMT, N.TOTAL_COM_AMT, N.SEM_PI_AMT, N.SEM_NI_AMT,
 N.SEM_RENEWAL_AMT, N.SEM_INCREASE_AMT, N.SEM_NEW_AMT, N.SEM_RENEWAL_COM, N.SEM_INCREASE_COM,
 N.SEM_NEW_COM, N.SEM_TOTAL_COM, N.COM_AMT, N.DEBIT_PRO_ADJ_COM_AMT, N.NET_COM_AMT,
 N.BEG_BALANCE_AMT, N.END_BALANCE_AMT, N.NEW_H1_CNT, N.TIP_H1_PCT, N.MTH_H1_NEW_AMT,
 N.MTH_H1_BONUS_AMT, N.MTH_H1_NET_BONUS_AMT, N.NEW_K1_CNT, N.TIP_K1_PCT, N.MTH_K1_NEW_AMT,
 N.MTH_K1_BONUS_AMT, N.MTH_K1_NET_BONUS_AMT, N.NEW_PE_CNT, N.TIP_PE_PCT, N.MTH_PE_NEW_AMT,
 N.MTH_PE_BONUS_AMT, N.MTH_PE_NET_BONUS_AMT, N.NEW_T1_NI_AMT, N.MTH_T1_NNI_AMT, N.MTH_T1_BONUS_AMT,
 N.TIP_T1_PCT, N.MTH_T1_NET_BONUS_AMT, N.NEW_T3_NI_AMT, N.MTH_T3_NNI_AMT, N.MTH_T3_BONUS_AMT,
 N.TIP_T3_PCT, N.MTH_T3_NET_BONUS_AMT, N.NEW_TA_NEW_CNT, N.MTH_TA_NNI_AMT, N.MTH_TA_BONUS_AMT,
 N.TIP_TA_PCT, N.MTH_TA_NET_BONUS_AMT, N.MTH_T2_NEW_AMT, N.MTH_T2_NEW_OBJ_AMT, N.MTH_T2_PERF_PCT,
 N.NEW_T2_CNT, N.MTH_T2_RATE, N.MTH_T2_TARGET_AMT, N.MTH_T2_BONUS_AMT, N.TIP_T2_PCT,
 N.MTH_T2_NET_BONUS_AMT, N.MTH_T4_NEW_AMT, N.MTH_T4_NEW_OBJ_AMT, N.MTH_T4_PERF_PCT, N.NEW_T4_CNT,
 N.MTH_T4_RATE, N.MTH_T4_TARGET_AMT, N.MTH_T4_BONUS_AMT, N.TIP_T4_PCT, N.MTH_T4_NET_BONUS_AMT,
 N.TOTAL_BONUS_DUE_AMT, N.BONUS_PAID_IND, N.TOTAL_BONUS_PAID_AMT, N.OTHER_INC_AMT, N.DISABILITY_INC_AMT,
 N.SA_INC_AMT, N.IST_TRAINING_INC_AMT, N.IST_TRANSITION_INC_AMT, N.OT_INC_AMT, N.ADJUST_INC_AMT,
 N.SA_TYPE, N.TOTAL_INCENTIVE_AMT, N.PRIOR_PAID_BALANCE_AMT, N.PRIOR_UNPAID_BALANCE_AMT, N.PAYMENT_AMT,
 N.OFFCYCLE_PAYMENTS_AMT, N.HIGH_PAYOUT_THLD_PCT, N.BUDGET_DAYS, N.IST_TRAINING_DAYS, N.IST_TRANSISTION_DAYS,
 N.STD_DAYS, N.TOTAL_DAYS, N.YTD_PI_AMT, N.YTD_NI_AMT, N.YTD_RENEWAL_AMT,
 N.YTD_INCREASE_AMT, N.YTD_NEWNON_AMT, N.YTD_RENEWAL_COM, N.YTD_INCREASE_COM, N.YTD_NEW_COM,
 N.YTD_COM, N.YTD_SEM_PI_AMT, N.YTD_SEM_NI_AMT, N.YTD_SEM_RENEWAL_AMT, N.YTD_SEM_INCREASE_AMT,
 N.YTD_SEM_NEW_AMT, N.YTD_SEM_RENEWAL_COM, N.YTD_SEM_INCREASE_COM, N.YTD_SEM_NEW_COM, N.YTD_SEM_TOTAL_COM,
 N.YTD_TOTAL_COM, N.YTD_TARGET_AMT, N.NEWNON_CNT, N.YTD_NEWNON_CNT, N.YTD_DEBIT_PRO_ADJ_COM_AMT,
 N.YTD_NET_COM_AMT, N.YTD_TOTAL_BONUS, N.BASE_PAY_AMT, N.YTD_BASE_PAY_AMT,
 N.PP_ACTIVE, N.YTD_ACTIVE_PP, N.YE_YTD_TOTAL_BONUS_AMT, N.YE_RESTART1_TOTAL_BONUS_AMT, N.YE_BONUS_COM_DUE,
 N.YE_BONUS_COM_PAID, N.YE_YTD_H1_PI_AMT, N.YE_YTD_H1_NI_AMT, N.YE_YTD_H1_SN_AMT, N.YE_YTD_H1_OBJ_PCT,
 N.YE_YTD_H1_OBJ_SN_AMT, N.YE_YTD_H1_RATE, N.YE_YTD_H1_RENEWAL_AMT, N.YE_YTD_H1_TIP_QUALIFY_IND, N.YE_YTD_H1_BONUS_AMT,
 N.YE_YTD_K1_PI_AMT, N.YE_YTD_K1_NI_AMT, N.YE_YTD_K1_SN_AMT, N.YE_YTD_K1_OBJ_PCT, N.YE_YTD_K1_OBJ_SN_AMT,
 N.YE_YTD_K1_RATE, N.YE_YTD_K1_RENEWAL_AMT, N.YE_YTD_K1_TIP_QUALIFY_IND, N.YE_YTD_K1_BONUS_AMT, N.YE_PE_YTD_NEW_AMT,
 N.YE_PE_YTD_NEW_OBJ_AMT, N.YE_YTD_PE_NEW_COUNT, N.YE_YTD_PE_NEW_OBJ_COUNT, N.YE_YTD_PE_BONUS_QUALIFY_IND, N.YE_YTD_PE_TIP_QUALIFY_IND,
 N.YE_YTD_PE_BONUS_AMT, N.YE_RESTART1_H1_PI_AMT, N.YE_RESTART1_H1_NI_AMT, N.YE_RESTART1_H1_SN_AMT, N.YE_RESTART1_H1_OBJ_PCT,
 N.YE_RESTART1_H1_OBJ_SN_AMT, N.YE_RESTART1_H1_RATE, N.YE_RESTART1_H1_RENEWAL_AMT, N.YE_RESTART1_H1_TIP_QUALIFY_IND, N.YE_RESTART1_H1_BONUS_AMT,
 N.YE_RESTART1_K1_PI_AMT, N.YE_RESTART1_K1_NI_AMT, N.YE_RESTART1_K1_SN_AMT, N.YE_RESTART1_K1_OBJ_PCT, N.YE_RESTART1_K1_OBJ_SN_AMT,
 N.YE_RESTART1_K1_RATE, N.YE_RESTART1_K1_RENEWAL_AMT, N.YE_RESTART1_K1_TIP_QUALIFY_IND, N.YE_RESTART1_K1_BONUS_AMT, N.YE_PE_RESTART1_NEW_AMT,
 N.YE_PE_RESTART1_NEW_OBJ_AMT, N.YE_RESTART1_PE_NEW_COUNT, N.YE_RESTART1_PE_NEW_OBJ_COUNT, N.YE_RESTART1_PE_BONUS_Q_IND, N.YE_RESTART1_PE_TIP_QUALIFY_IND,
 N.YE_RESTART1_PE_BONUS_AMT, N.EXTRACT_DATE, N.BONUS_TARGET_AMT, N.YTD_BONUS_TARGET_AMT
FROM
 HRW.FINREPO_PH_NCCP_PP_DETAIL_VW@HRWP.WORLD N;
 
COMMIT;                      
 
 --------------------------------------------------------------

/***** LOAD FINREPO_SCP_REP_LIST_VW BASED ON SELECTED PAY PERIODS *****/
TRUNCATE TABLE FINCOMM.FINCOMM_SCP_REP_LIST;

INSERT INTO FINCOMM.FINCOMM_SCP_REP_LIST
 (PAY_PERIOD_ID, KGEN_PAYEEID, CSS_PAYEEID, PP_YEAR, PP_NUM,
 VZID, USER_ID, EMPLOYEE_STATUS, 
 HR_HIRE_DATE, HIRE_DATE, TERMINATE_DATE, DIV_CODE_NUM, EMPLOYEE_UNIT,
 CHANNEL, PAY_TYPE, POSITION, TITLE_CODE, CLOCK_ID, 
 OFFICE_CODE, DSM_NUM, DM_NUM, TC_ACTIVE_IND, TC_PLAN_NAME,
 COLA_RATES_IND, EXTRACT_DATE, REP_NAME, PP_CALANDAR, RVP_NUM,
 OFFICE_NAME, OFFICE_STATE, DSM_NAME, DM_NAME, RVP_NAME,
 REGION_NAME, CREATED_BY, CREATED_DATE, LAST_UPDATED_BY, LAST_UPDATE_DATE)
 
SELECT /*+ DRIVING_SITE(R) */
 R.PAY_PERIOD_ID, R.KGEN_PAYEEID, R.CSS_PAYEEID, R.PP_YEAR, R.PP_NUM,
 R.VZID, R.USER_ID, R.EMPLOYEE_STATUS,
 R.HR_HIRE_DATE, R.HIRE_DATE, R.TERMINATE_DATE, R.DIV_CODE_NUM, R.EMPLOYEE_UNIT,
 R.CHANNEL, R.PAY_TYPE, R.POSITION, R.TITLE_CODE, R.CLOCK_ID, 
 R.OFFICE_CODE, R.DSM_NUM, R.DM_NUM, R.TC_ACTIVE_IND, R.TC_PLAN_NAME,
 R.COLA_RATES_IND, R.EXTRACT_DATE, R.REP_NAME, R.PP_CALANDAR, R.RVP_NUM,
 R.OFFICE_NAME, R.OFFICE_STATE, R.DSM_NAME, R.DM_NAME, R.RVP_NAME,
 R.REGION_NAME, 'HRWP', SYSDATE, 'HRWP', SYSDATE
FROM 
 HRW.FINREPO_SCP_REP_LIST_VW@HRWP.WORLD R;
 
COMMIT;
                      
                                            
/***** RELOAD ALL FINREPO_PP_INCENTIVE_DATA_VW *****/                      
TRUNCATE TABLE FINCOMM.FINCOMM_PP_INCENTIVE_DATA;

INSERT INTO FINCOMM.FINCOMM_PP_INCENTIVE_DATA
 (EMPLOYEE_ID, ERN_PAY_PERIOD_DTE, ERN_CDE, ERN_DESC, ERN_AMT, REP_NUM)

SELECT
 EMPLOYEE_ID, ERN_PAY_PERIOD_DTE, ERN_CDE, ERN_DESC, ERN_AMT, REP_NUM
FROM 
 HRW.FINREPO_PP_INCENTIVE_DATA_VW@HRWP.WORLD;
COMMIT;

/****** MANUALLY CHANGE THE TO_BE_PROCESSED VALES IN COM_HR_JEID_PP *****/
